# Generated by Django 4.2.11 on 2024-04-01 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationArticleBody',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('article_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_body_content', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_changed_by_user', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_retired_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_article_body',
            },
        ),
        migrations.CreateModel(
            name='EducationArticleHeader',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('article_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_header_content', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('article_body_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_article_header_article_body', to='education.educationarticlebody')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_changed_by_user', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_retired_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_article_header',
            },
        ),
    ]
