# Generated by Django 4.2.11 on 2024-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_maintenance',
            },
        ),
    ]
