"""
Django settings for ddac_application project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(t)u9!s!3!&sh^*f@$nppgdw1ig24@cfb6_c!3-!hs0q7k4e+='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# CHANGE DEFAULT USER MODEL
AUTH_USER_MODEL = 'account.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'education',
    'food',
    'general',
    'sustainable',
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ddac_application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ddac_application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
##LOCAL DATABASE
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2',
#             'NAME': 'postgres',
#             'USER': 'admin',
#             'PASSWORD': '',
#             'HOST': 'localhost',
#             'PORT': '5440',
#     }
# }

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'ddac_db',
            'USER': 'ddac_admin',
            'PASSWORD': 'password',
            'HOST': 'ddacdb.c52e4ck2g5ru.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'ddac_application/static'
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'custom_login_page'


AWS_ACCESS_KEY_ID = 'ASIAU6GDY54H4PTJUO6W'
AWS_SECRET_ACCESS_KEY = '9hE42//fCCJMbcBUsZScqhfqjr2wS62H33dsybYS'
AWS_SESSION_TOKEN='IQoJb3JpZ2luX2VjENv//////////wEaCXVzLXdlc3QtMiJGMEQCIDJJca6MhUr5vKCu5rQXZHU0F7vlHinQSH/HDokj9MSwAiB0+dYud1IMR8AhbTU65TaerfkPCkqne8df1zJa8xIL7yqkAggUEAAaDDMzOTcxMjk5NTA4NyIMsDKw9CV2L3TE8LbWKoECn0VE4rzSIiFOD+idBXMSFgPRCi7gvU2D+FqiuAiLHh1pk4QebGn3Of3x1ti2CeDpMkBhWGqrUCSxEkp6Kgqe7U0Y/6YmCYfNkUBRy+sjPaTEVAyJ6V2swO4ioQeQRAo5mJIWgxLsgoMfOXSYHG/+fIAlWD55UCuazIas6LTSA6WQrPKJb3jOakkmDBi/LxC8BLgd+tXizk5Om30xxpcGasX/EjgSi2vYkFaUE6A6TZ9iLtAS49hclBkKvGn9eDZuhRVO+OmwNVr4iVi4Ve+MPN0qt3su8+oRxSexysSklrN7A6OP13ADqDYWvh7AU1yvQZVTOAecf3xFW7abpciVnhgwn8HUsAY6ngFgbH+zK8qKRYOgw5CZ6VUiXjU2Szksm6m2bvil8smcbrRPRBIw9BRweQLa0eqjjhGoX/+XNSuUn3/+CqILIIWpiFxtZcBwBlyYTBmx+zXWmK7WaiFEjRg15HDsRV7h8Z0XU6GhmqjlbgOUxOI9xkLpb5n1uKNVPEAgV9yCG7I0Olv6JwuGm09uZMlzvI19qhPao7Z0SkE7/JxC/VY8MQ=='
AWS_STORAGE_BUCKET_NAME = 'ddac-bucket'
AWS_S3_REGION_NAME = 'us-east-1'  # e.g., us-east-1
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# For serving static files directly from S3
AWS_S3_URL_PROTOCOL = 'https:'
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True

# Static and media file configuration
# STATIC_URL = f'{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/static/'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_URL = f'{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/media/'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'