"""
Django settings for ddac_application project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(t)u9!s!3!&sh^*f@$nppgdw1ig24@cfb6_c!3-!hs0q7k4e+='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# CHANGE DEFAULT USER MODEL
AUTH_USER_MODEL = 'account.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'education',
    'food',
    'general',
    'sustainable',
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ddac_application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ddac_application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
##LOCAL DATABASE
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2',
#             'NAME': 'postgres',
#             'USER': 'admin',
#             'PASSWORD': '',
#             'HOST': 'localhost',
#             'PORT': '5440',
#     }
# }

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'sustainabledb',
            'USER': 'cloudadmin',
            'PASSWORD': '12345678',
            'HOST': 'clouddb.c1ykq6y6m32e.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'ddac_application/static'
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'custom_login_page'


AWS_ACCESS_KEY_ID = 'ASIA47CRYXX3H5XKPCPG'
AWS_SECRET_ACCESS_KEY = '4zvxwkkhQAhJu1VCikyR8M9VS6qQt70m4gr5L8TX'
AWS_SESSION_TOKEN='IQoJb3JpZ2luX2VjEBIaCXVzLXdlc3QtMiJHMEUCIE7KDVq70dMjYhDereKaE0fvjsPicrejU/jNO7V3e0GSAiEAwFgV7vPFPszSITGVW0o0gl/tKjc8lGoQySuMeJ3Q8f8qsgIISxAAGgw4OTEzNzcyMDQ3MjYiDAonhj1J1V3oEyftTSqPAogqec5eVO1+LopQsRC/ndENTkLAGMtIjnM2bJbAEjn2vA98cFeFGdDkBQjRSQWre5pAPAp3YGTUZw/SBVA1MlhBQOIsY9RnvgSduPyPVvBQleVsPEsW6NNGetJDMs8m7KDCP6V84evxxARMiWYJY8xFLwnhtc6od37tzjG2wsncJVNMzB/86yRmcJXTFLT9ZHnmSNVwQoZJ6Bczz08Igqc+7Vy+9SlWSIjDWYus2Y01JhoyvvxOqCFVlAbD9OWxbPwTCrgPiUltKxY2pM7kz9tRUYD5t3olChn68Odz1dOsDNXPe5Gxh792R/b3IT/lb9cDyptPSlxXk5rr5e6usi0JI+xW0lmytDFyf8Ne/C8wp7zgsAY6nQHcDR3ZHlFmKtH2I/bxuOije0+Z1SMpP9DC7QvA4rTVsWUsuEiU6jGC5Vv5dmHxLO0Fjt4ywarJi7aC0v6BZBuBszjVseveTuvzB3eF96uD+HPRG8IYCrPOMf+u5/d+JHEzNmoS22rhvdH4nbW0m/K36x5u/vc/GEFA5GUQovHYtHqfvUBwT/MT9DFrlFEzOcb5TU1YbomPsAW/7iuw'
# AWS_STORAGE_BUCKET_NAME = 'ddac-bucket'
# AWS_S3_REGION_NAME = 'us-east-1'  # e.g., us-east-1
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# # For serving static files directly from S3
# AWS_S3_URL_PROTOCOL = 'https:'
# AWS_S3_USE_SSL = True
# AWS_S3_VERIFY = True

# # Static and media file configuration
# # STATIC_URL = f'{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/static/'
# # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# MEDIA_URL = f'{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/media/'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'